"""Generate a device-local CA + IP certificate and an ISOLATED nginx configuration.

No root keys or certificates ship with this project. No global nginx/tunnel
config is edited. A manually trusted private CA has wide signing power: keep its
key private and remove the CA from client trust stores when retiring the hub.
"""
from __future__ import annotations
import argparse, hashlib, ipaddress, os, shutil, subprocess, sys, time
from pathlib import Path


def run(*args, capture=False):
    return subprocess.run(list(map(str,args)), check=True, stdout=subprocess.PIPE if capture else subprocess.DEVNULL,
                          stderr=subprocess.PIPE, text=True).stdout


def quote(path):
    text=str(path)
    if any(x in text for x in ['\n','\r','\x00']):raise ValueError('Invalid path')
    return '"'+text.replace('\\','\\\\').replace('"','\\"').replace('$','\\$')+'"'


def setup(root: Path, ip: str, port: int=8443, renew=False):
    address=ipaddress.IPv4Address(ip)
    if not address.is_private or address.is_loopback or address.is_unspecified:
        raise ValueError('Use the private LAN IPv4 address reserved for V35.')
    if port in {8088,8080,8022} or not 1024<=port<=65535:raise ValueError('Use a separate unprivileged HTTPS port, normally 8443.')
    if not shutil.which('openssl'):raise ValueError('Install openssl-tool in Termux first.')
    root=root.resolve();dest=root/'data/https';dest.mkdir(parents=True,exist_ok=True,mode=0o700)
    if dest.is_symlink():raise ValueError('HTTPS directory must not be a symlink')
    private=dest/'private';public=dest/'public';private.mkdir(exist_ok=True,mode=0o700);public.mkdir(exist_ok=True,mode=0o700)
    ca=private/'ca.crt';key=private/'ca.key';leaf=private/'server.crt';leafkey=private/'server.key'
    if ca.exists()!=key.exists():raise ValueError('Partial CA files exist. Inspect or restore; do not regenerate the trusted root blindly.')
    if not key.exists():
        run('openssl','req','-x509','-newkey','rsa:3072','-nodes','-sha256','-days','3650',
            '-subj','/CN=Room Hub Private Root CA', '-addext','basicConstraints=critical,CA:TRUE,pathlen:0',
            '-addext','keyUsage=critical,keyCertSign,cRLSign', '-keyout',key,'-out',ca)
    valid=False
    if leaf.exists() and leafkey.exists() and not renew:
        try:
            run('openssl','verify','-CAfile',ca,'-verify_ip',ip,leaf)
            run('openssl','x509','-checkend','2592000','-noout','-in',leaf)
            valid=True
        except subprocess.CalledProcessError:pass
    if not valid:
        serial=str(int.from_bytes(os.urandom(16),'big'));csr=private/'server.csr';ext=private/'server.ext'
        ext.write_text(f'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\nsubjectAltName=IP:{ip},IP:127.0.0.1,DNS:localhost\nsubjectKeyIdentifier=hash\nauthorityKeyIdentifier=keyid,issuer\n')
        run('openssl','req','-new','-newkey','rsa:2048','-nodes','-sha256','-subj','/CN=Room Hub LAN',
            '-keyout',leafkey,'-out',csr)
        run('openssl','x509','-req','-in',csr,'-CA',ca,'-CAkey',key,'-set_serial',serial,
            '-out',leaf,'-days','180','-sha256','-extfile',ext)
        csr.unlink(missing_ok=True);ext.unlink(missing_ok=True)
    run('openssl','verify','-CAfile',ca,'-verify_ip',ip,leaf)
    run('openssl','x509','-in',ca,'-outform','DER','-out',public/'roomhub-ca.cer')
    for f in private.iterdir():f.chmod(0o600)
    for name in ['client','proxy']:(dest/'tmp'/name).mkdir(parents=True,exist_ok=True,mode=0o700)
    config=f'''# Generated by Room Hub setup_https.py. Separate from existing nginx:8080.
worker_processes 1;
pid {quote(dest/'nginx.pid')};
error_log stderr warn;
events {{ worker_connections 256; }}
http {{
  access_log off;
  client_body_temp_path {quote(dest/'tmp/client')};
  proxy_temp_path {quote(dest/'tmp/proxy')};
  map $http_upgrade $connection_upgrade {{ default upgrade; '' close; }}
  server {{
    listen {port} ssl;
    server_name _;
    ssl_certificate {quote(leaf)};
    ssl_certificate_key {quote(leafkey)};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:ROOMHUBSSL:1m;
    client_max_body_size 10m;
    client_body_timeout 45s;
    location / {{
      proxy_pass http://127.0.0.1:8088;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_read_timeout 90s;
      proxy_send_timeout 60s;
      proxy_request_buffering off;
      proxy_buffering off;
      proxy_cookie_flags ~ secure httponly samesite=strict;
    }}
  }}
}}
'''
    conf=dest/'nginx.conf'
    if conf.exists():
        previous=conf.read_text()
        if not previous.startswith('# Generated by Room Hub setup_https.py.'):
            raise ValueError('Existing nginx config was not generated by this tool; no overwrite.')
    conf.write_text(config);conf.chmod(0o600)
    (dest/'certificate-fingerprint.txt').write_text(run('openssl','x509','-in',ca,'-noout','-fingerprint','-sha256',capture=True))
    print('HTTPS configuration:',conf)
    print('Certificate valid for 180 days; --renew reissues only the leaf, keeping the same trusted CA.')
    print('Share ONLY:',public/'roomhub-ca.cer')
    print((dest/'certificate-fingerprint.txt').read_text().strip())
    print(f'iPad: https://{ip}:{port}/client')
    return dest


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--root',type=Path,default=Path(__file__).resolve().parents[2]);p.add_argument('--ip',required=True);p.add_argument('--port',type=int,default=8443);p.add_argument('--renew',action='store_true')
    a=p.parse_args()
    try:setup(a.root,a.ip,a.port,a.renew)
    except (ValueError,OSError,subprocess.CalledProcessError) as e:
        print('STOP:',str(e),file=sys.stderr);return 1
    return 0
if __name__=='__main__':raise SystemExit(main())
